CREATE SEQUENCE DEPT
    INCREMENT BY 10     --  INTERVALOS ENTRE OS NÚMERO DA SEQUÊNCIA
    START WITH 500        -- O PRIMEIRO NÚMERO GERADO PELA SEQUÊNCIA
    MAXVALUE 9999        --  O VALOR MÁXIMO QUE A SEQUÊNCIA PODE RETORNAR
-- NOMAXVALUE            --  NÃO HAVERÁ LIMITE MÁXIMO DE VALOR
-- MINVALUE                   --  O VALOR MÍNIMO QUE A SEQUÊNCIA PODE RETORNAR
-- NOMINVALUE             --  NÃO HAVERÁ LIMITE MÍNIMO DE VALOR
-- CYCLE                          --  SE O NÚMERO DA SEQUÊNCIA VOLTA AO VALOR MÍNIMO DEPOIS DE ATINGIR O VALOR MÁXIMO(SEQUÊNCIA ASCENDENTES)
    NOCYCLE                    --  SE O NÚMERO DA SEQUÊNCIA VOLTA AO VALOR MÁXIMO DEPOIS DE ATINGIR O VALOR MÍNIMO(SEQUÊNCIA DESCENDENTES)
-- CACHE                        --   ESPECIFICA O NÚMERO DE SEQUÊNCIA QUE SERÁ GUARDADO NA MEMÓRIA. VALOR MIN = 2 E DEFAULT = 20   
    NOCACHE                 --   NÃO GUARDA SEQUÊNCIA NA MEMÓRIA
-- ORDER                      --   UTILIZAR QUANDO FOR SERVIDOR PARALELO COM A OPÇÃO DE MODO COMPARTILHADO.GARANTIR QUE O NÚMERO
                                        --   DE SEQUÊNCIA SEJA GERADO EM ORDEM REQUERIDA
-- NOORDER              --     ORDEM NORMAL DO NÚMERO DA SEQUÊNCIA
    ;
    
INSERT INTO departments(department_id, department_name, location_id) 
VALUES (DEPT.NEXTVAL, 'Support', 2500);

select * from departments;

SELECT DEPT.CURRVAL
FROM DUAL;

delete from departments where department_id = 500;



    